version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=oni_data
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oni_data
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db_data:
