# Generated by Django 5.0.3 on 2024-03-14 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=3, max_digits=13, verbose_name="Nominal Value"
                    ),
                ),
                (
                    "amount_of_payments",
                    models.PositiveIntegerField(
                        default=12, verbose_name="Amount of Payments"
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="Interest Rate"
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "request_date",
                    models.DateField(auto_now_add=True, verbose_name="Request Date"),
                ),
                (
                    "bank",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Bank"
                    ),
                ),
                (
                    "client",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Client"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
