# Generated by Django 5.0.3 on 2024-03-14 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=3, max_digits=13, verbose_name="Payment Value"
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=3, max_digits=13, verbose_name="Total Value"
                    ),
                ),
                (
                    "interest_value",
                    models.DecimalField(
                        decimal_places=3, max_digits=13, verbose_name="Interest Value"
                    ),
                ),
                ("date", models.DateField(verbose_name="Payment Date")),
                ("due_date", models.DateField(verbose_name="Due Date")),
                (
                    "installment_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Installment Number"
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Is Paid")),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="loan.loan",
                    ),
                ),
            ],
        ),
    ]
